version: '3'
services:
  web:
    image: djangotodo_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    container_name: web
    depends_on:
      - db

  db:
    image: djangotodo_db
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: db
